---
- hosts: zabbix-agent2
  become: true
  tasks:

   - name: Create Agent2 Volume
     docker_volume:
      name: agent2-data

   - name: Create Zabbix-Agent2 Container
     community.docker.docker_container:
      name: "zabbix-agent2"
      image: zabbix/zabbix-agent2:alpine-6.2.4
      hostname: ladytech_zabbixagent
      restart_policy: "always"
      restart: true
      ports:
       - "10050:10050"

      volumes:
        - agent2-data:/etc/zabbix/
      env:
          ZBX_HOSTNAME: "ladytech_zabbixagent"
          ZBX_SERVER_HOST: ""
      networks:
       - name: vira
      cpus: "2"
      memory: "2"
